---
development:
  cloud_name: gagoit
  api_key: '989237415483897'
  api_secret: _QtVDXhYP5BKl_ahjBEPnJT6Gu8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: gagoit
  api_key: '989237415483897'
  api_secret: _QtVDXhYP5BKl_ahjBEPnJT6Gu8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: gagoit
  api_key: '989237415483897'
  api_secret: _QtVDXhYP5BKl_ahjBEPnJT6Gu8
  enhance_image_tag: true
  static_image_support: false
